// Package genutil provides utilities for generating Go code from configuration data.
package genutil

import (
	"encoding/json"
	"fmt"
	"maps"
	"os"
	"regexp"
	"sort"
	"strings"
)

// FuncParam represents a function parameter configuration.
type FuncParam struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// ContractDefinition represents a parsed contract JSON file.
type ContractDefinition struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Request     struct {
		Meta struct {
			Method  string `json:"method"`
			Path    string `json:"path"`
			BaseURL string `json:"baseURL"`
		} `json:"meta"`
		Example map[string]any `json:"example"`
		Mutable map[string]any `json:"mutable"`
		Structs map[string]any `json:"structs"` // string (path) or map[string]string (field composition)
		Func    struct {
			Params []FuncParam `json:"params"`
		} `json:"func"`
	} `json:"request"`
	Response struct {
		Meta struct {
			StatusCode  int    `json:"statusCode"`
			ContentType string `json:"contentType"`
		} `json:"meta"`
		Example any            `json:"example"`
		Mutable map[string]any `json:"mutable"`
		Structs map[string]any `json:"structs"` // string (path) or map[string]string (field composition)
	} `json:"response"`
}

// ContractGenConfig holds configuration for contract code generation.
type ContractGenConfig struct {
	JSONPath       string
	PackageName    string
	OutputFileName string
	BaseURLConst   string
}

// GenerateContract generates Go Contract code from a JSON definition file.
func GenerateContract(cfg ContractGenConfig) (map[string]string, error) {
	data, err := os.ReadFile(cfg.JSONPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read json file: %w", err)
	}

	var def ContractDefinition
	if err := json.Unmarshal(data, &def); err != nil {
		return nil, fmt.Errorf("failed to parse json: %w", err)
	}

	if cfg.PackageName == "" {
		cfg.PackageName = "client"
	}
	if cfg.OutputFileName == "" {
		cfg.OutputFileName = toSnakeCase(def.Name) + "_contract.go"
	}
	if cfg.BaseURLConst == "" {
		cfg.BaseURLConst = "BaseURL"
	}

	code := generateContractCode(def, cfg)
	return map[string]string{cfg.OutputFileName: code}, nil
}

const ContractFileSuffix = ".contract.json"

// GenerateContractsFromDir generates Contract code from all *.contract.json files in a directory.
func GenerateContractsFromDir(dir, pkgName string) (map[string]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	result := make(map[string]string)
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ContractFileSuffix) {
			continue
		}

		files, err := GenerateContract(ContractGenConfig{
			JSONPath:    dir + "/" + entry.Name(),
			PackageName: pkgName,
		})
		if err != nil {
			return nil, fmt.Errorf("failed to generate %s: %w", entry.Name(), err)
		}
		maps.Copy(result, files)
	}

	return result, nil
}

func generateContractCode(def ContractDefinition, cfg ContractGenConfig) string {
	g := &contractGenerator{
		def:           def,
		cfg:           cfg,
		nestedStructs: make([]string, 0),
		pathToStruct:  make(map[string]string),
	}
	return g.generate()
}

type contractGenerator struct {
	def           ContractDefinition
	cfg           ContractGenConfig
	nestedStructs []string
	pathToStruct  map[string]string // path -> struct name (reverse lookup)
	currentPath   string
	isRequest     bool
	allExample    map[string]any // flattened example data for path resolution
}

func (g *contractGenerator) generate() string {
	var sb strings.Builder

	sb.WriteString("// Code generated by nexus genutil. DO NOT EDIT.\n")
	fmt.Fprintf(&sb, "package %s\n\n", g.cfg.PackageName)

	sb.WriteString("import (\n")
	sb.WriteString("\t\"bytes\"\n")
	sb.WriteString("\t\"encoding/json\"\n")
	sb.WriteString("\t\"io\"\n")
	sb.WriteString(")\n\n")

	var structs []string
	g.isRequest = true

	// Build path->struct mapping from request.structs
	g.buildPathToStructMap(g.def.Request.Structs)

	// Build flattened example for request
	g.allExample = g.buildFlatExample()

	// Generate structs from request.structs (simple and composite)
	requestStructs := g.generateStructsFromConfig(g.def.Request.Structs)
	structs = append(structs, requestStructs...)

	// Generate request query struct if exists
	queryStructName := ""
	if query, ok := g.def.Request.Example["query"].(map[string]any); ok && len(query) > 0 {
		if name, ok := g.pathToStruct["query"]; ok {
			queryStructName = name
		} else {
			queryStructName = g.def.Name + "Query"
		}
		g.currentPath = "query"
		structs = append(structs, g.generateStructBody(queryStructName, query))
	}

	// Generate request body struct if exists
	reqStructName := ""
	if body, ok := g.def.Request.Example["body"].(map[string]any); ok && len(body) > 0 {
		if name, ok := g.pathToStruct["body"]; ok {
			reqStructName = name
		} else {
			reqStructName = g.def.Name + "Request"
		}
		g.currentPath = "body"
		structs = append(structs, g.generateStructBody(reqStructName, body))
	}

	// Collect request nested structs
	requestNestedStructs := g.nestedStructs
	g.nestedStructs = make([]string, 0)

	// Switch to response
	g.isRequest = false
	g.pathToStruct = make(map[string]string)
	g.buildPathToStructMap(g.def.Response.Structs)

	// Generate structs from response.structs
	responseStructs := g.generateStructsFromConfig(g.def.Response.Structs)
	structs = append(structs, responseStructs...)

	// Generate response struct if exists
	respStructName := ""
	if resp, ok := g.def.Response.Example.(map[string]any); ok && len(resp) > 0 {
		respStructName = g.def.Name + "Response"
		g.currentPath = ""
		structs = append(structs, g.generateStructBody(respStructName, resp))
	}

	// Add nested structs
	for i := len(requestNestedStructs) - 1; i >= 0; i-- {
		structs = append(structs, requestNestedStructs[i])
	}
	for i := len(g.nestedStructs) - 1; i >= 0; i-- {
		structs = append(structs, g.nestedStructs[i])
	}

	// Output type block
	if len(structs) > 0 {
		sb.WriteString("type (\n")
		for i, s := range structs {
			sb.WriteString(s)
			if i < len(structs)-1 {
				sb.WriteString("\n")
			}
		}
		sb.WriteString(")\n\n")
	}

	sb.WriteString(g.generateContractFunc(queryStructName, reqStructName, respStructName))
	return sb.String()
}

// buildPathToStructMap builds reverse lookup: path -> struct name
func (g *contractGenerator) buildPathToStructMap(structs map[string]any) {
	for structName, value := range structs {
		switch v := value.(type) {
		case string:
			// Simple mapping: "TeacherInfo": "body.teacher"
			g.pathToStruct[v] = structName
		}
		// Composite mappings don't contribute to pathToStruct
	}
}

// buildFlatExample builds flattened example including path params
func (g *contractGenerator) buildFlatExample() map[string]any {
	result := make(map[string]any)

	// Add example data (pathParams is now part of example)
	for k, v := range g.def.Request.Example {
		result[k] = v
	}

	// Fallback: if pathParams not in example, extract from path template for backward compatibility
	if _, hasPathParams := result["pathParams"]; !hasPathParams {
		pathParams := extractPathParams(g.def.Request.Meta.Path)
		if len(pathParams) > 0 {
			pathData := make(map[string]any)
			for _, p := range pathParams {
				pathData[p] = "" // string type for path params (fallback)
			}
			result["pathParams"] = pathData
		}
	}

	return result
}

// generateStructsFromConfig generates structs from structs config
func (g *contractGenerator) generateStructsFromConfig(structs map[string]any) []string {
	var result []string

	for structName, value := range structs {
		switch v := value.(type) {
		case string:
			// Simple mapping: generate struct from path
			// Will be handled by inferGoType when processing parent
			continue
		case map[string]any:
			// Composite mapping: custom field composition
			result = append(result, g.generateCompositeStruct(structName, v))
		}
	}

	return result
}

// generateCompositeStruct generates struct with custom field composition
func (g *contractGenerator) generateCompositeStruct(name string, fields map[string]any) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "\t%s struct {\n", name)

	// Sort fields for deterministic output
	keys := make([]string, 0, len(fields))
	for k := range fields {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, key := range keys {
		var fieldName, fieldType, jsonTag string

		// Check if key is a struct reference: @structs.StructName or @structs.StructName[FieldName]
		if strings.HasPrefix(key, "@structs.") {
			structRef := strings.TrimPrefix(key, "@structs.")
			structName, customFieldName := parseStructRef(structRef)

			if customFieldName != "" {
				fieldName = customFieldName
			} else {
				fieldName = structName
			}
			fieldType = structName
			jsonTag = toSnakeCaseLower(fieldName)
		} else {
			// Regular field: FieldName -> sourcePath
			fieldName = key
			sourcePath, ok := fields[key].(string)
			if !ok {
				continue
			}
			fieldType = g.resolveTypeFromPath(sourcePath)
			jsonTag = toSnakeCaseLower(fieldName)
		}

		fmt.Fprintf(&sb, "\t\t%s %s `json:\"%s\"`\n", fieldName, fieldType, jsonTag)
	}

	sb.WriteString("\t}\n")
	return sb.String()
}

// parseStructRef parses "StructName" or "StructName[FieldName]" and returns (structName, fieldName)
func parseStructRef(ref string) (string, string) {
	if idx := strings.Index(ref, "["); idx != -1 {
		structName := ref[:idx]
		fieldName := strings.TrimSuffix(ref[idx+1:], "]")
		return structName, fieldName
	}
	return ref, ""
}

// resolveTypeFromPath resolves Go type from example path
func (g *contractGenerator) resolveTypeFromPath(path string) string {
	value := g.getValueFromPath(path)
	if value == nil {
		return "any"
	}

	switch v := value.(type) {
	case string:
		return "string"
	case float64:
		if v == float64(int64(v)) {
			return "int"
		}
		return "float64"
	case bool:
		return "bool"
	case map[string]any:
		// Check if this path has a struct defined
		if structName, ok := g.pathToStruct[path]; ok {
			return structName
		}
		return "any"
	case []any:
		if len(v) == 0 {
			return "[]any"
		}
		switch v[0].(type) {
		case string:
			return "[]string"
		case float64:
			return "[]float64"
		case bool:
			return "[]bool"
		default:
			return "[]any"
		}
	default:
		return "any"
	}
}

// getValueFromPath gets value from flattened example by path
func (g *contractGenerator) getValueFromPath(path string) any {
	parts := strings.Split(path, ".")
	var current any = g.allExample

	for _, part := range parts {
		if m, ok := current.(map[string]any); ok {
			current = m[part]
		} else {
			return nil
		}
	}

	return current
}

func (g *contractGenerator) generateContractFunc(queryStructName, reqStructName, respStructName string) string {
	var sb strings.Builder

	pathParams := extractPathParams(g.def.Request.Meta.Path)

	responseType := "any"
	if respStructName != "" {
		responseType = respStructName
	}

	if g.def.Description != "" {
		fmt.Fprintf(&sb, "// %s %s\n", g.def.Name, g.def.Description)
	}
	fmt.Fprintf(&sb, "var %s = func(", g.def.Name)

	// Check if custom func.params is defined
	if len(g.def.Request.Func.Params) > 0 {
		g.generateCustomFuncParams(&sb, responseType, pathParams)
	} else {
		g.generateDefaultFuncParams(&sb, queryStructName, reqStructName, responseType, pathParams)
	}

	return sb.String()
}

func (g *contractGenerator) generateDefaultFuncParams(sb *strings.Builder, queryStructName, reqStructName, responseType string, pathParams []string) {
	params := make([]string, 0)
	for _, p := range pathParams {
		params = append(params, p+" string")
	}
	if queryStructName != "" {
		params = append(params, "query *"+queryStructName)
	}
	if reqStructName != "" {
		params = append(params, "body *"+reqStructName)
	}
	sb.WriteString(strings.Join(params, ", "))
	fmt.Fprintf(sb, ") *Contract[%s] {\n", responseType)

	urlExpr := g.buildURLExpr(pathParams)
	fmt.Fprintf(sb, "\treturn &Contract[%s]{\n", responseType)
	sb.WriteString("\t\tURL:    " + urlExpr + ",\n")

	if g.def.Request.Meta.Method != "" && g.def.Request.Meta.Method != "GET" {
		sb.WriteString("\t\tMethod: \"" + g.def.Request.Meta.Method + "\",\n")
	}

	if reqStructName != "" {
		sb.WriteString("\t\tBody:   toJSONReader(body),\n")
	}

	sb.WriteString("\t}\n")
	sb.WriteString("}\n\n")

	if reqStructName != "" {
		sb.WriteString("func toJSONReader(v any) io.Reader {\n")
		sb.WriteString("\tdata, _ := json.Marshal(v)\n")
		sb.WriteString("\treturn bytes.NewReader(data)\n")
		sb.WriteString("}\n")
	}
}

func (g *contractGenerator) generateCustomFuncParams(sb *strings.Builder, responseType string, pathParams []string) {
	funcParams := g.def.Request.Func.Params

	// Generate function parameters
	params := make([]string, 0, len(funcParams))
	for _, p := range funcParams {
		params = append(params, p.Name+" *"+p.Type)
	}
	sb.WriteString(strings.Join(params, ", "))
	fmt.Fprintf(sb, ") *Contract[%s] {\n", responseType)

	// Analyze struct fields to find path/query/body sources
	pathSources := make(map[string]string)  // pathParam -> "paramName.FieldName"
	querySources := make(map[string]string) // queryField -> "paramName.FieldName"
	var bodyParam string

	for _, p := range funcParams {
		structDef, ok := g.def.Request.Structs[p.Type]
		if !ok {
			continue
		}

		switch v := structDef.(type) {
		case string:
			// Simple mapping: check if it's body
			if v == "body" {
				bodyParam = p.Name
			}
		case map[string]any:
			// Composite mapping: analyze field sources
			for fieldName, sourcePath := range v {
				if strings.HasPrefix(fieldName, "@structs.") {
					continue
				}
				source, ok := sourcePath.(string)
				if !ok {
					continue
				}
				if strings.HasPrefix(source, "pathParams.") {
					pathField := strings.TrimPrefix(source, "pathParams.")
					pathSources[pathField] = p.Name + "." + fieldName
				} else if strings.HasPrefix(source, "query.") {
					queryField := strings.TrimPrefix(source, "query.")
					querySources[queryField] = p.Name + "." + fieldName
				} else if source == "body" {
					bodyParam = p.Name + "." + fieldName
				}
			}
		}
	}

	// Build URL expression with custom sources
	urlExpr := g.buildURLExprWithSources(pathParams, pathSources)
	fmt.Fprintf(sb, "\treturn &Contract[%s]{\n", responseType)
	sb.WriteString("\t\tURL:    " + urlExpr + ",\n")

	if g.def.Request.Meta.Method != "" && g.def.Request.Meta.Method != "GET" {
		sb.WriteString("\t\tMethod: \"" + g.def.Request.Meta.Method + "\",\n")
	}

	if bodyParam != "" {
		sb.WriteString("\t\tBody:   toJSONReader(" + bodyParam + "),\n")
	}

	sb.WriteString("\t}\n")
	sb.WriteString("}\n\n")

	if bodyParam != "" {
		sb.WriteString("func toJSONReader(v any) io.Reader {\n")
		sb.WriteString("\tdata, _ := json.Marshal(v)\n")
		sb.WriteString("\treturn bytes.NewReader(data)\n")
		sb.WriteString("}\n")
	}
}

func (g *contractGenerator) buildURLExprWithSources(pathParams []string, pathSources map[string]string) string {
	path := g.def.Request.Meta.Path
	baseURL := g.cfg.BaseURLConst

	if g.def.Request.Meta.BaseURL != "" {
		baseURL = fmt.Sprintf("\"%s\"", g.def.Request.Meta.BaseURL)
	}

	if len(pathParams) == 0 {
		return fmt.Sprintf("%s + \"%s\"", baseURL, path)
	}

	var parts []string
	remaining := path
	for _, p := range pathParams {
		placeholder := "{" + p + "}"
		idx := strings.Index(remaining, placeholder)
		if idx == -1 {
			continue
		}
		if idx > 0 {
			parts = append(parts, fmt.Sprintf("\"%s\"", remaining[:idx]))
		}
		// Use custom source if available, otherwise use param directly
		if source, ok := pathSources[p]; ok {
			parts = append(parts, source)
		} else {
			parts = append(parts, p)
		}
		remaining = remaining[idx+len(placeholder):]
	}
	if remaining != "" {
		parts = append(parts, fmt.Sprintf("\"%s\"", remaining))
	}

	if len(parts) == 0 {
		return baseURL + " + \"" + path + "\""
	}
	return baseURL + " + " + strings.Join(parts, " + ")
}

func (g *contractGenerator) buildURLExpr(pathParams []string) string {
	path := g.def.Request.Meta.Path
	baseURL := g.cfg.BaseURLConst

	if g.def.Request.Meta.BaseURL != "" {
		baseURL = fmt.Sprintf("\"%s\"", g.def.Request.Meta.BaseURL)
	}

	if len(pathParams) == 0 {
		return fmt.Sprintf("%s + \"%s\"", baseURL, path)
	}

	var parts []string
	remaining := path
	for _, p := range pathParams {
		placeholder := "{" + p + "}"
		idx := strings.Index(remaining, placeholder)
		if idx == -1 {
			continue
		}
		if idx > 0 {
			parts = append(parts, fmt.Sprintf("\"%s\"", remaining[:idx]))
		}
		parts = append(parts, p)
		remaining = remaining[idx+len(placeholder):]
	}
	if remaining != "" {
		parts = append(parts, fmt.Sprintf("\"%s\"", remaining))
	}

	if len(parts) == 0 {
		return baseURL + " + \"" + path + "\""
	}
	return baseURL + " + " + strings.Join(parts, " + ")
}

func (g *contractGenerator) generateStructBody(name string, data map[string]any) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "\t%s struct {\n", name)

	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, key := range keys {
		value := data[key]
		fieldName := toPascalCase(key)
		fieldType := g.inferGoType(key, value)
		fmt.Fprintf(&sb, "\t\t%s %s `json:\"%s\"`\n", fieldName, fieldType, key)
	}

	sb.WriteString("\t}\n")
	return sb.String()
}

func (g *contractGenerator) inferGoType(key string, value any) string {
	var path string
	if g.currentPath == "" {
		path = key
	} else {
		path = g.currentPath + "." + key
	}

	switch v := value.(type) {
	case string:
		return "string"
	case float64:
		if v == float64(int64(v)) {
			return "int"
		}
		return "float64"
	case bool:
		return "bool"
	case map[string]any:
		// Check if declared in structs
		if structName, ok := g.pathToStruct[path]; ok {
			savedPath := g.currentPath
			g.currentPath = path
			g.nestedStructs = append(g.nestedStructs, g.generateStructBody(structName, v))
			g.currentPath = savedPath
			return structName
		}
		return g.generateInlineStruct(path, v)
	case []any:
		return g.inferSliceType(key, path, v)
	default:
		return "any"
	}
}

func (g *contractGenerator) generateInlineStruct(path string, data map[string]any) string {
	var sb strings.Builder
	sb.WriteString("struct {\n")

	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	savedPath := g.currentPath
	g.currentPath = path

	for _, key := range keys {
		value := data[key]
		fieldName := toPascalCase(key)
		fieldType := g.inferGoType(key, value)
		fmt.Fprintf(&sb, "\t\t\t%s %s `json:\"%s\"`\n", fieldName, fieldType, key)
	}

	g.currentPath = savedPath
	sb.WriteString("\t\t}")
	return sb.String()
}

func (g *contractGenerator) inferSliceType(key, path string, slice []any) string {
	if len(slice) == 0 {
		return "[]any"
	}

	switch first := slice[0].(type) {
	case string:
		return "[]string"
	case float64:
		return "[]float64"
	case bool:
		return "[]bool"
	case map[string]any:
		if structName, ok := g.pathToStruct[path]; ok {
			savedPath := g.currentPath
			g.currentPath = path
			g.nestedStructs = append(g.nestedStructs, g.generateStructBody(structName, first))
			g.currentPath = savedPath
			return "[]" + structName
		}
		return "[]" + g.generateInlineStruct(path, first)
	default:
		return "[]any"
	}
}

func extractPathParams(path string) []string {
	re := regexp.MustCompile(`\{(\w+)\}`)
	matches := re.FindAllStringSubmatch(path, -1)
	params := make([]string, 0, len(matches))
	for _, m := range matches {
		params = append(params, m[1])
	}
	return params
}

func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteByte('_')
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}

func toSnakeCaseLower(s string) string {
	return strings.ToLower(s[:1]) + s[1:]
}