// Package genutil provides utilities for generating Go code from configuration data.
package genutil

import (
	"fmt"
	"strings"
)

// Framework conventions (hardcoded defaults)
const (
	// defaultEnvKey is the key path for environment config in YAML.
	// Must match cmd.DefaultEnvKey - this is a framework convention.
	DefaultEnvKey = "nexus.environment"

	// Default values for code generation
	DefaultPackageName    = "main"
	DefaultStructName     = "Environment"
	DefaultMainFileName   = "main.go"
	DefaultConfigFileName = "config_gen.go"
)

// ProgramConfig holds the configuration for generating a nexus program scaffold.
//
// Example usage:
//
//	files, err := genutil.GenerateProgram(genutil.ProgramConfig{
//	    PackageName: "main",
//	    YAMLPath:    "nexus.yaml",
//	})
//	for filename, content := range files {
//	    os.WriteFile(filename, []byte(content), 0644)
//	}
type ProgramConfig struct {
	// PackageName is the package name for generated files. Default: "main"
	PackageName string

	// StructName is the name of the config struct (e.g., "ServerConfig").
	// If empty but YAMLPath is provided, defaults to "Environment".
	// If both empty, program function will use map[string]any as env type.
	StructName string

	// YAMLPath is the path to the YAML configuration file.
	// If empty, no config struct file will be generated.
	YAMLPath string

	// OutputDir is the directory to output generated files. Default: current directory.
	OutputDir string

	// WithLogger controls whether to generate logger initialization code. Default: true
	WithLogger bool

	// MainFileName is the output filename for main.go. Default: "main.go"
	MainFileName string

	// ConfigFileName is the output filename for config struct. Default: "config_gen.go"
	ConfigFileName string
}

// GenerateProgram generates a nexus project scaffold including main.go and config struct.
// It returns a map of filename to file content.
//
// Generated files:
//   - main.go: Contains the main function and program function skeleton
//   - config_gen.go: Contains the config struct (if YAMLPath and StructName are provided)
func GenerateProgram(cfg ProgramConfig) (map[string]string, error) {
	// Set defaults
	if cfg.PackageName == "" {
		cfg.PackageName = DefaultPackageName
	}
	if cfg.MainFileName == "" {
		cfg.MainFileName = DefaultMainFileName
	}
	if cfg.ConfigFileName == "" {
		cfg.ConfigFileName = DefaultConfigFileName
	}
	// If YAMLPath is provided but StructName is not, use default struct name
	if cfg.YAMLPath != "" && cfg.StructName == "" {
		cfg.StructName = DefaultStructName
	}

	result := make(map[string]string)

	// Generate config struct if YAML path is provided (using fixed EnvKey)
	if cfg.YAMLPath != "" && cfg.StructName != "" {
		structCode, err := GenerateStructFromYAML(cfg.YAMLPath, DefaultEnvKey, cfg.PackageName, cfg.StructName)
		if err != nil {
			return nil, fmt.Errorf("generate struct failed: %w", err)
		}
		result[cfg.ConfigFileName] = structCode
	}

	// Generate main.go
	mainCode := generateMainFile(cfg)
	result[cfg.MainFileName] = mainCode

	return result, nil
}

// generateMainFile generates the main.go file content
func generateMainFile(cfg ProgramConfig) string {
	var sb strings.Builder

	// File header
	sb.WriteString("// Generated by nexus genutil scaffold.\n")
	fmt.Fprintf(&sb, "package %s\n\n", cfg.PackageName)

	// Imports
	sb.WriteString("import (\n")
	sb.WriteString("\t\"context\"\n")
	sb.WriteString("\n")
	sb.WriteString("\t\"github.com/vkviyu/nexus/cmd\"\n")
	if cfg.WithLogger {
		sb.WriteString("\t\"github.com/vkviyu/nexus/utils/logutil\"\n")
	}
	sb.WriteString(")\n\n")

	// program function - use concrete type if StructName provided, otherwise map[string]any
	if cfg.StructName != "" {
		fmt.Fprintf(&sb, "func program(stopctx context.Context, config %s, cleanUpDone chan error) {\n", cfg.StructName)
		sb.WriteString("\t_ = config // TODO: Use config and implement business logic here\n")
	} else {
		sb.WriteString("func program(stopctx context.Context, env map[string]any, cleanUpDone chan error) {\n")
		sb.WriteString("\t_ = env // TODO: Use env and implement business logic here\n")
	}
	sb.WriteString("\n")
	sb.WriteString("\t// Wait for stop signal\n")
	sb.WriteString("\t<-stopctx.Done()\n")
	sb.WriteString("\t// TODO: Clean up resources\n")
	sb.WriteString("\n")
	sb.WriteString("\t// Notify cleanup complete\n")
	sb.WriteString("\tcleanUpDone <- nil\n")
	sb.WriteString("}\n\n")

	// main function
	sb.WriteString("func main() {\n")
	if cfg.WithLogger {
		sb.WriteString("\tlogger, err := logutil.NewRotateLogger(nil)\n")
		sb.WriteString("\tif err != nil {\n")
		sb.WriteString("\t\tpanic(err)\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\t_ = logger\n")
		sb.WriteString("\n")
	}
	// Use generic NewNexusCmd with appropriate type parameter
	if cfg.StructName != "" {
		fmt.Fprintf(&sb, "\tserverCmd := cmd.NewNexusCmd[%s](program)\n", cfg.StructName)
	} else {
		sb.WriteString("\tserverCmd := cmd.NewNexusCmd[map[string]any](program)\n")
	}
	sb.WriteString("\tif err := serverCmd.Execute(); err != nil {\n")
	sb.WriteString("\t\tpanic(err)\n")
	sb.WriteString("\t}\n")
	sb.WriteString("}\n")

	return sb.String()
}