// Package genutil provides utilities for generating Go struct code from configuration data.
package genutil

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode"

	"github.com/go-viper/mapstructure/v2"
	"github.com/vkviyu/nexus/utils/maputil"
	"gopkg.in/yaml.v3"
)

// GenerateStructFromMap generates Go struct code from a map[string]any.
// It returns the generated code as a string.
//
// Parameters:
//   - data: the map containing the struct field data
//   - pkgName: the package name for the generated file
//   - structName: the name of the root struct (e.g., "Environment", "Config")
func GenerateStructFromMap(data map[string]any, pkgName, structName string) (string, error) {
	if data == nil {
		data = make(map[string]any)
	}

	g := &generator{
		nestedStructs: make([]string, 0),
	}

	var sb strings.Builder

	// File header
	sb.WriteString("// Code generated by nexus genutil. DO NOT EDIT.\n")
	fmt.Fprintf(&sb, "package %s\n\n", pkgName)

	// Generate main struct
	sb.WriteString(g.generateStructDef(structName, data))

	// Generate nested structs (reverse order for dependency)
	for i := len(g.nestedStructs) - 1; i >= 0; i-- {
		sb.WriteString("\n")
		sb.WriteString(g.nestedStructs[i])
	}

	return sb.String(), nil
}

// GenerateStructFromYAML reads a YAML file, extracts the specified key content,
// and returns the generated Go struct code as a string.
//
// Parameters:
//   - yamlPath: path to the YAML configuration file
//   - envKey: dot-separated key path to extract (e.g., "nexus.environment")
//   - pkgName: the package name for the generated file
//   - structName: the name of the root struct
//
// Example:
//
//	code, err := genutil.GenerateStructFromYAML("nexus.yaml", "nexus.environment", "Environment", "main")
//	if err != nil {
//	    return err
//	}
//	os.WriteFile("env_gen.go", []byte(code), 0644)
func GenerateStructFromYAML(yamlPath, envKey, pkgName, structName string) (string, error) {
	data, err := os.ReadFile(yamlPath)
	if err != nil {
		return "", fmt.Errorf("failed to read yaml file: %w", err)
	}

	var root map[string]any
	if err := yaml.Unmarshal(data, &root); err != nil {
		return "", fmt.Errorf("failed to parse yaml: %w", err)
	}

	target, err := maputil.GetNestedMap(root, envKey)
	if err != nil {
		return "", err
	}

	return GenerateStructFromMap(target, pkgName, structName)
}

type generator struct {
	nestedStructs []string
}

func (g *generator) generateStructDef(name string, data map[string]any) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "type %s struct {\n", name)

	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, key := range keys {
		value := data[key]
		fieldName := toPascalCase(key)
		fieldType := g.inferGoType(key, value)
		fmt.Fprintf(&sb, "\t%s %s `json:\"%s\" yaml:\"%s\" mapstructure:\"%s\"`\n",
			fieldName, fieldType, key, key, key)
	}

	sb.WriteString("}\n")
	return sb.String()
}

func (g *generator) inferGoType(key string, value any) string {
	switch v := value.(type) {
	case string:
		return "string"
	case int:
		return "int"
	case int64:
		return "int64"
	case float64:
		if v == float64(int64(v)) {
			return "int"
		}
		return "float64"
	case bool:
		return "bool"
	case map[string]any:
		structName := toPascalCase(key)
		g.nestedStructs = append(g.nestedStructs, g.generateStructDef(structName, v))
		return structName
	case []any:
		return g.inferSliceType(key, v)
	default:
		return "any"
	}
}

func (g *generator) inferSliceType(key string, slice []any) string {
	if len(slice) == 0 {
		return "[]any"
	}

	switch first := slice[0].(type) {
	case string:
		return "[]string"
	case int, int64:
		return "[]int"
	case float64:
		return "[]float64"
	case bool:
		return "[]bool"
	case map[string]any:
		elemName := toPascalCase(key) + "Item"
		g.nestedStructs = append(g.nestedStructs, g.generateStructDef(elemName, first))
		return "[]" + elemName
	default:
		return "[]any"
	}
}

func toPascalCase(s string) string {
	var sb strings.Builder
	capitalizeNext := true

	for _, r := range s {
		if r == '_' || r == '-' || r == '.' {
			capitalizeNext = true
			continue
		}
		if capitalizeNext {
			sb.WriteRune(unicode.ToUpper(r))
			capitalizeNext = false
		} else {
			sb.WriteRune(r)
		}
	}

	return sb.String()
}

// ParseStruct converts map[string]any to *T struct using mapstructure.
// This is a generic replacement for the previously generated Parse* functions.
//
// Example:
//
//	config, err := genutil.ParseStruct[ServerConfig](envMap)
//	if err != nil {
//	    return err
//	}
func ParseStruct[T any](data map[string]any) (*T, error) {
	var result T
	if err := mapstructure.Decode(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
