// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClient(arg1, arg2) {
  return window['go']['main']['App']['AddClient'](arg1, arg2);
}

export function AddClientDomain(arg1) {
  return window['go']['main']['App']['AddClientDomain'](arg1);
}

export function AddSavedRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSavedRequest'](arg1, arg2, arg3);
}

export function AddServer(arg1, arg2) {
  return window['go']['main']['App']['AddServer'](arg1, arg2);
}

export function AddServerDomain(arg1) {
  return window['go']['main']['App']['AddServerDomain'](arg1);
}

export function AddTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTab'](arg1, arg2, arg3);
}

export function DeleteClient(arg1, arg2) {
  return window['go']['main']['App']['DeleteClient'](arg1, arg2);
}

export function DeleteClientDomain(arg1) {
  return window['go']['main']['App']['DeleteClientDomain'](arg1);
}

export function DeleteSavedRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteSavedRequest'](arg1, arg2, arg3);
}

export function DeleteServer(arg1, arg2) {
  return window['go']['main']['App']['DeleteServer'](arg1, arg2);
}

export function DeleteServerDomain(arg1) {
  return window['go']['main']['App']['DeleteServerDomain'](arg1);
}

export function DeleteTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteTab'](arg1, arg2, arg3);
}

export function EmitViewAction(arg1) {
  return window['go']['main']['App']['EmitViewAction'](arg1);
}

export function EmitViewSet(arg1, arg2) {
  return window['go']['main']['App']['EmitViewSet'](arg1, arg2);
}

export function EmitViewToggle(arg1) {
  return window['go']['main']['App']['EmitViewToggle'](arg1);
}

export function GetActualPort(arg1) {
  return window['go']['main']['App']['GetActualPort'](arg1);
}

export function GetAllClientDomains() {
  return window['go']['main']['App']['GetAllClientDomains']();
}

export function GetAllServerDomains() {
  return window['go']['main']['App']['GetAllServerDomains']();
}

export function GetClient(arg1, arg2) {
  return window['go']['main']['App']['GetClient'](arg1, arg2);
}

export function GetClientDomain(arg1) {
  return window['go']['main']['App']['GetClientDomain'](arg1);
}

export function GetDBPath() {
  return window['go']['main']['App']['GetDBPath']();
}

export function GetSavedRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSavedRequest'](arg1, arg2, arg3);
}

export function GetServer(arg1, arg2) {
  return window['go']['main']['App']['GetServer'](arg1, arg2);
}

export function GetServerDomain(arg1) {
  return window['go']['main']['App']['GetServerDomain'](arg1);
}

export function GetServerStatus(arg1) {
  return window['go']['main']['App']['GetServerStatus'](arg1);
}

export function GetServerStatuses() {
  return window['go']['main']['App']['GetServerStatuses']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTab'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadWorkspace() {
  return window['go']['main']['App']['LoadWorkspace']();
}

export function ResolveServerURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveServerURL'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWorkspace(arg1) {
  return window['go']['main']['App']['SaveWorkspace'](arg1);
}

export function SendRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2, arg3, arg4);
}

export function SendTabRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendTabRequest'](arg1, arg2, arg3);
}

export function StartServer(arg1, arg2) {
  return window['go']['main']['App']['StartServer'](arg1, arg2);
}

export function StopServer(arg1, arg2) {
  return window['go']['main']['App']['StopServer'](arg1, arg2);
}

export function UpdateClient(arg1, arg2) {
  return window['go']['main']['App']['UpdateClient'](arg1, arg2);
}

export function UpdateClientDomain(arg1) {
  return window['go']['main']['App']['UpdateClientDomain'](arg1);
}

export function UpdateSavedRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSavedRequest'](arg1, arg2, arg3);
}

export function UpdateServer(arg1, arg2) {
  return window['go']['main']['App']['UpdateServer'](arg1, arg2);
}

export function UpdateServerDomain(arg1) {
  return window['go']['main']['App']['UpdateServerDomain'](arg1);
}

export function UpdateTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTab'](arg1, arg2, arg3);
}
