// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {main} from '../models';

export function AddClient(arg1:string,arg2:domain.Client):Promise<void>;

export function AddClientDomain(arg1:domain.ClientDomain):Promise<void>;

export function AddSavedRequest(arg1:string,arg2:string,arg3:domain.SavedRequest):Promise<domain.SavedRequest>;

export function AddServer(arg1:string,arg2:domain.Server):Promise<void>;

export function AddServerDomain(arg1:domain.ServerDomain):Promise<void>;

export function AddTab(arg1:string,arg2:string,arg3:domain.RequestTab):Promise<void>;

export function DeleteClient(arg1:string,arg2:string):Promise<void>;

export function DeleteClientDomain(arg1:string):Promise<void>;

export function DeleteSavedRequest(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteServer(arg1:string,arg2:string):Promise<void>;

export function DeleteServerDomain(arg1:string):Promise<void>;

export function DeleteTab(arg1:string,arg2:string,arg3:string):Promise<void>;

export function EmitViewAction(arg1:string):Promise<void>;

export function EmitViewSet(arg1:string,arg2:boolean):Promise<void>;

export function EmitViewToggle(arg1:string):Promise<void>;

export function GetActualPort(arg1:string):Promise<number>;

export function GetAllClientDomains():Promise<Array<domain.ClientDomain>>;

export function GetAllServerDomains():Promise<Array<domain.ServerDomain>>;

export function GetClient(arg1:string,arg2:string):Promise<domain.Client>;

export function GetClientDomain(arg1:string):Promise<domain.ClientDomain>;

export function GetDBPath():Promise<string>;

export function GetSavedRequest(arg1:string,arg2:string,arg3:string):Promise<domain.SavedRequest>;

export function GetServer(arg1:string,arg2:string):Promise<domain.Server>;

export function GetServerDomain(arg1:string):Promise<domain.ServerDomain>;

export function GetServerStatus(arg1:string):Promise<string>;

export function GetServerStatuses():Promise<Record<string, string>>;

export function GetSettings():Promise<domain.Settings>;

export function GetTab(arg1:string,arg2:string,arg3:string):Promise<domain.RequestTab>;

export function Greet(arg1:string):Promise<string>;

export function LoadWorkspace():Promise<domain.Workspace>;

export function ResolveServerURL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveSettings(arg1:domain.Settings):Promise<void>;

export function SaveWorkspace(arg1:domain.Workspace):Promise<void>;

export function SendRequest(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string):Promise<main.RequestResult>;

export function SendTabRequest(arg1:string,arg2:string,arg3:string):Promise<main.RequestResult>;

export function StartServer(arg1:string,arg2:string):Promise<void>;

export function StopServer(arg1:string,arg2:string):Promise<void>;

export function UpdateClient(arg1:string,arg2:domain.Client):Promise<void>;

export function UpdateClientDomain(arg1:domain.ClientDomain):Promise<void>;

export function UpdateSavedRequest(arg1:string,arg2:string,arg3:domain.SavedRequest):Promise<void>;

export function UpdateServer(arg1:string,arg2:domain.Server):Promise<void>;

export function UpdateServerDomain(arg1:domain.ServerDomain):Promise<void>;

export function UpdateTab(arg1:string,arg2:string,arg3:domain.RequestTab):Promise<void>;
