// Code generated by nexus genutil. DO NOT EDIT.
package main

type ServerConfig struct {
	Host string `json:"host" yaml:"host" mapstructure:"host"`
	Port string `json:"port" yaml:"port" mapstructure:"port"`
}
