// Generated by nexus genutil scaffold.
package main

import (
	"context"

	"github.com/vkviyu/nexus/cmd"
	"github.com/vkviyu/nexus/utils/logutil"
)

func program(stopctx context.Context, config ServerConfig, cleanUpDone chan error) {
	_ = config // TODO: Use config and implement business logic here

	// Wait for stop signal
	<-stopctx.Done()
	// TODO: Clean up resources

	// Notify cleanup complete
	cleanUpDone <- nil
}

func main() {
	logger, err := logutil.NewRotateLogger(nil)
	if err != nil {
		panic(err)
	}
	_ = logger

	serverCmd := cmd.NewNexusCmd(program)
	if err := serverCmd.Execute(); err != nil {
		panic(err)
	}
}
