// Code generated by nexus genutil. DO NOT EDIT.
package example

import (
	"bytes"
	"encoding/json"
	"io"

	"github.com/vkviyu/nexus/transport/client"
)

type (
	ClassParams struct {
		SchoolID int    `json:"schoolID"`
		Semester string `json:"semester"`
		Year     int    `json:"year"`
	}

	CreateClassQuery struct {
		Semester string `json:"semester"`
		Year     int    `json:"year"`
	}

	CreateClassBody struct {
		ClassId   string        `json:"classId"`
		ClassName string        `json:"className"`
		Students  []StudentItem `json:"students"`
		Teacher   TeacherInfo   `json:"teacher"`
	}

	CreateClassResponse struct {
		CreatedAt string      `json:"createdAt"`
		Data      ClassResult `json:"data"`
		Id        int         `json:"id"`
	}

	TeacherInfo struct {
		Age      int      `json:"age"`
		Name     string   `json:"name"`
		Subjects []string `json:"subjects"`
	}

	StudentItem struct {
		Name  string `json:"name"`
		Score int    `json:"score"`
	}

	ClassResult struct {
		ClassInfo ClassDetail `json:"classInfo"`
		Success   bool        `json:"success"`
	}

	ClassDetail struct {
		Id           string `json:"id"`
		StudentCount int    `json:"studentCount"`
	}
)

// CreateClass Create a new class in the specified school
var CreateClass = func(schoolId string, query *CreateClassQuery, body *CreateClassBody) *client.Contract[CreateClassResponse] {
	return &client.Contract[CreateClassResponse]{
		URL:    "https://api.example.com" + "/classes/" + schoolId,
		Method: "POST",
		Body:   toJSONReader(body),
	}
}

func toJSONReader(v any) io.Reader {
	data, _ := json.Marshal(v)
	return bytes.NewReader(data)
}
